spring:
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/duckji?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username:
    password:
  data:
    mongodb:
      username: duckji
      password: duckji123
      uri: mongodb://localhost:${database}
      database: duckji
  mongodb:
    embedded:
      version: 4.0.12